logging:
  level: INFO
  loggers:
    com.example: DEBUG

server:
  type: default
  maxThreads: 1024

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: tayal12345
  url: jdbc:mysql://localhost/data