logging:
  level: INFO
  loggers:
    com.example: DEBUG


database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: tayal12345
  url: jdbc:mysql://localhost:3306:DWGettingStarted

server:
  type: default
  maxThreads: 1024

